apiVersion: v1
kind: Pod
metadata:
  name: shop-pod
spec:
  containers:
  - name: shop
    image: busybox
    command: ["sh", "-c", "env && sleep 3600"]
    envFrom:
    - configMapRef:
        name: shop-config
