apiVersion: v1
kind: Secret
metadata:
  name: shop-secret
type: Opaque
data:
  DB_PASSWORD: czNjdXIzLXBAc3N3MHJk
---
apiVersion: v1
kind: Pod
metadata:
  name: shop-pod
spec:
  containers:
  - name: shop
    image: busybox
    command: ["sh", "-c", "env && sleep 3600"]
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: shop-secret
          key: DB_PASSWORD
